# Generated by Django 5.0.2 on 2024-02-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=2500)),
                ('place', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('Center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.center')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.client')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=2500)),
                ('place', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.client')),
            ],
        ),
    ]
