# Generated by Django 5.0.2 on 2024-02-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_center_ticketcenter_tickettech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcenter',
            name='client',
        ),
    ]
