# Generated by Django 5.0.2 on 2024-02-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_feedback_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Type',
        ),
        migrations.AddField(
            model_name='feedback',
            name='center',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
