# Generated by Django 5.0.2 on 2024-02-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_remove_feedback_type_feedback_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client',
        ),
    ]
