# Generated by Django 5.0.2 on 2024-02-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_feedback_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettech',
            name='Client',
        ),
        migrations.AddField(
            model_name='tickettech',
            name='center',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickettech',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickettech',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tickettech',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
